import type { Event, Category, User, Testimonial } from "./types"

// Sample categories
export const categories: Category[] = [
  {
    id: "cat_1",
    name: "Concerts",
    description: "Live music performances",
    icon: "music",
    slug: "concerts",
    eventCount: 12,
  },
  {
    id: "cat_2",
    name: "Conferences",
    description: "Professional gatherings and talks",
    icon: "users",
    slug: "conferences",
    eventCount: 8,
  },
  {
    id: "cat_3",
    name: "Workshops",
    description: "Hands-on learning experiences",
    icon: "tool",
    slug: "workshops",
    eventCount: 15,
  },
  {
    id: "cat_4",
    name: "Sports",
    description: "Athletic competitions and games",
    icon: "activity",
    slug: "sports",
    eventCount: 10,
  },
  {
    id: "cat_5",
    name: "Exhibitions",
    description: "Art and cultural showcases",
    icon: "image",
    slug: "exhibitions",
    eventCount: 7,
  },
  {
    id: "cat_6",
    name: "Parties",
    description: "Social gatherings and celebrations",
    icon: "party-popper",
    slug: "parties",
    eventCount: 9,
  },
  
    {
  id: "cat_7",
  name: "Alumni Summit",
  description: "College alumni reunion and networking events",
  icon: "graduation-cap",
  slug: "alumni",
  eventCount: 6,
},
  
  {
    id: "cat_8",
    name: "Festivals",
    description: "Cultural and seasonal celebrations",
    icon: "sparkles",
    slug: "festivals",
    eventCount: 11,
  },
]

// Sample events
export const events: Event[] = [
  {
    id: "event_1",
    title: "Summer Music Festival",
    description: "A three-day music festival featuring top artists from around the world.",
    date: "2025-07-15",
    time: "12:00 PM",
    location: "Central Park, New York",
    category: "Concerts",
    price: 150,
    image: "/placeholder.svg?height=400&width=600",
    organizerId: "user_2",
    attendees: 5000,
    isFeatured: true,
    createdAt: "2025-01-15T10:30:00Z",
  },
  {
    id: "event_2",
    title: "Tech Conference 2025",
    description: "The biggest tech conference of the year with keynotes from industry leaders.",
    date: "2025-06-10",
    time: "9:00 AM",
    location: "Convention Center, San Francisco",
    category: "Conferences",
    price: 299,
    image: "/placeholder.svg?height=400&width=600",
    organizerId: "user_2",
    attendees: 3000,
    isFeatured: true,
    createdAt: "2025-01-20T14:45:00Z",
  },
  {
    id: "event_3",
    title: "Web Development Workshop",
    description: "Learn the latest web development techniques from industry experts.",
    date: "2025-05-20",
    time: "10:00 AM",
    location: "Tech Hub, Austin",
    category: "Workshops",
    price: 50,
    image: "/placeholder.svg?height=400&width=600",
    organizerId: "user_2",
    attendees: 100,
    isFeatured: false,
    createdAt: "2025-02-01T09:15:00Z",
  },
  {
    id: "event_4",
    title: "Championship Basketball Game",
    description: "The final game of the season with the top two teams competing for the championship.",
    date: "2025-05-05",
    time: "7:30 PM",
    location: "Sports Arena, Chicago",
    category: "Sports",
    price: 75,
    image: "/placeholder.svg?height=400&width=600",
    organizerId: "user_3",
    attendees: 15000,
    isFeatured: true,
    createdAt: "2025-02-10T11:20:00Z",
  },
  {
    id: "event_5",
    title: "Modern Art Exhibition",
    description: "A showcase of contemporary art from emerging artists around the world.",
    date: "2025-06-15",
    time: "11:00 AM",
    location: "Metropolitan Museum, New York",
    category: "Exhibitions",
    price: 25,
    image: "/placeholder.svg?height=400&width=600",
    organizerId: "user_3",
    attendees: 500,
    isFeatured: false,
    createdAt: "2025-02-15T16:30:00Z",
  },
  {
    id: "event_6",
    title: "New Year's Eve Party",
    description: "Ring in the new year with music, dancing, and a midnight countdown.",
    date: "2025-12-31",
    time: "8:00 PM",
    location: "Grand Hotel, Las Vegas",
    category: "Parties",
    price: 100,
    image: "/placeholder.svg?height=400&width=600",
    organizerId: "user_2",
    attendees: 1000,
    isFeatured: true,
    createdAt: "2025-03-01T13:45:00Z",
  },
  {
    id: "event_7",
    title: "Alumni Summit",
    description: "A grand alumni reunion event for networking, reconnecting and celebrating achievements.",
    date: "2025-06-20",
    time: "10:00 AM",
    location: "Vadodara, Gujarat",
    category: "Alumni Summit",
    price: 0,
    image: "/images/alumni.jpg",
    organizerId: "user_3",
    attendees: 150,
    isFeatured: false,
    createdAt: "2025-03-10T10:00:00Z",
  },
  {
    id: "event_8",
    title: "Food & Wine Festival",
    description: "Sample cuisine and wines from top chefs and vineyards.",
    date: "2025-07-10",
    time: "1:00 PM",
    location: "Waterfront Park, San Diego",
    category: "Festivals",
    price: 85,
    image: "/placeholder.svg?height=400&width=600",
    organizerId: "user_2",
    attendees: 2500,
    isFeatured: true,
    createdAt: "2025-03-15T15:20:00Z",
  },
  {
    id: "event_9",
    title: "Jazz Night",
    description: "An evening of smooth jazz with renowned musicians.",
    date: "2025-05-15",
    time: "8:00 PM",
    location: "Blue Note Jazz Club, New Orleans",
    category: "Concerts",
    price: 40,
    image: "/placeholder.svg?height=400&width=600",
    organizerId: "user_3",
    attendees: 200,
    isFeatured: false,
    createdAt: "2025-03-20T09:30:00Z",
  },
  {
    id: "event_10",
    title: "AI and Machine Learning Summit",
    description: "Explore the latest advancements in artificial intelligence and machine learning.",
    date: "2025-08-05",
    time: "9:30 AM",
    location: "Tech Center, Seattle",
    category: "Conferences",
    price: 199,
    image: "/placeholder.svg?height=400&width=600",
    organizerId: "user_2",
    attendees: 800,
    isFeatured: true,
    createdAt: "2025-04-01T11:15:00Z",
  },
  {
    id: "event_11",
    title: "Photography Workshop",
    description: "Learn advanced photography techniques from professional photographers.",
    date: "2025-05-25",
    time: "10:00 AM",
    location: "Creative Studio, Portland",
    category: "Workshops",
    price: 75,
    image: "/placeholder.svg?height=400&width=600",
    organizerId: "user_3",
    attendees: 50,
    isFeatured: false,
    createdAt: "2025-04-05T14:00:00Z",
  },
  {
    id: "event_12",
    title: "Marathon Race",
    description: "A 26.2-mile race through the scenic city streets.",
    date: "2025-09-10",
    time: "7:00 AM",
    location: "Downtown, Boston",
    category: "Sports",
    price: 50,
    image: "/placeholder.svg?height=400&width=600",
    organizerId: "user_2",
    attendees: 5000,
    isFeatured: true,
    createdAt: "2025-04-10T08:45:00Z",
  },
  {
    id: "event_13",
    title: "Historical Artifacts Exhibition",
    description: "A display of rare historical artifacts from around the world.",
    date: "2025-07-20",
    time: "10:00 AM",
    location: "History Museum, Washington DC",
    category: "Exhibitions",
    price: 15,
    image: "/placeholder.svg?height=400&width=600",
    organizerId: "user_3",
    attendees: 300,
    isFeatured: false,
    createdAt: "2025-04-15T13:30:00Z",
  },
  {
    id: "event_14",
    title: "Halloween Costume Party",
    description: "A spooky celebration with prizes for the best costumes.",
    date: "2025-10-31",
    time: "8:00 PM",
    location: "Haunted Mansion, Salem",
    category: "Parties",
    price: 30,
    image: "/placeholder.svg?height=400&width=600",
    organizerId: "user_2",
    attendees: 400,
    isFeatured: true,
    createdAt: "2025-04-20T16:15:00Z",
  },
  {
    id: "event_15",
    title: "Alumni Summit",
    description: "A grand alumni reunion event where graduates reconnect, network and celebrate achievements.",
    date: "2025-08-15",
    time: "10:00 AM",
    location: "Vadodara, Gujarat",
    category: "Alumni Summit",
    price: 0,
    image: "/images/alumni.jpg",
    organizerId: "user_3",
    attendees: 100,
    isFeatured: false,
    createdAt: "2025-04-25T10:45:00Z",
  },
  {
    id: "event_16",
    title: "Cultural Heritage Festival",
    description: "Celebrate diverse cultures with food, music, and traditional performances.",
    date: "2025-06-25",
    time: "11:00 AM",
    location: "Community Park, San Francisco",
    category: "Festivals",
    price: 10,
    image: "/placeholder.svg?height=400&width=600",
    organizerId: "user_2",
    attendees: 1500,
    isFeatured: true,
    createdAt: "2025-05-01T12:00:00Z",
  },
  {
    id: "event_17",
    title: "Rock Concert",
    description: "A high-energy rock concert featuring popular bands.",
    date: "2025-05-30",
    time: "7:00 PM",
    location: "Stadium, Los Angeles",
    category: "Concerts",
    price: 65,
    image: "/placeholder.svg?height=400&width=600",
    organizerId: "user_3",
    attendees: 10000,
    isFeatured: false,
    createdAt: "2025-05-05T15:30:00Z",
  },
  {
    id: "event_18",
    title: "Startup Pitch Competition",
    description: "Entrepreneurs pitch their startup ideas to investors and judges.",
    date: "2025-07-05",
    time: "1:00 PM",
    location: "Innovation Hub, Austin",
    category: "Conferences",
    price: 0,
    image: "/placeholder.svg?height=400&width=600",
    organizerId: "user_2",
    attendees: 250,
    isFeatured: true,
    createdAt: "2025-05-10T09:00:00Z",
  },
  {
    id: "event_19",
    title: "Cooking Masterclass",
    description: "Learn to cook gourmet meals from a celebrity chef.",
    date: "2025-06-05",
    time: "5:00 PM",
    location: "Culinary Institute, Chicago",
    category: "Workshops",
    price: 120,
    image: "/placeholder.svg?height=400&width=600",
    organizerId: "user_3",
    attendees: 30,
    isFeatured: false,
    createdAt: "2025-05-15T14:15:00Z",
  },
  {
    id: "event_20",
    title: "Tennis Tournament",
    description: "Watch professional tennis players compete in this annual tournament.",
    date: "2025-08-20",
    time: "10:00 AM",
    location: "Tennis Center, Miami",
    category: "Sports",
    price: 45,
    image: "/placeholder.svg?height=400&width=600",
    organizerId: "user_2",
    attendees: 2000,
    isFeatured: true,
    createdAt: "2025-05-20T11:45:00Z",
  },
]

// Sample users
export const users: User[] = [
  {
    id: "user_1",
    name: "Admin User",
    email: "admin@example.com",
    role: "admin",
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "user_2",
    name: "Event Organizer",
    email: "organizer@example.com",
    role: "organizer",
    createdAt: "2025-01-05T00:00:00Z",
  },
  {
    id: "user_3",
    name: "Event Attendee",
    email: "attendee@example.com",
    role: "attendee",
    createdAt: "2025-01-10T00:00:00Z",
  },
]

// Sample testimonials
export const testimonials: Testimonial[] = [
  {
    id: "testimonial_1",
    name: "Sarah Johnson",
    role: "Event Attendee",
    content:
      "I've attended multiple events through this platform and each one has been amazing. The booking process is so simple!",
    avatar: "/placeholder.svg?height=100&width=100",
    rating: 5,
  },
  {
    id: "testimonial_2",
    name: "Michael Chen",
    role: "Event Organizer",
    content:
      "As an organizer, this platform has made it incredibly easy to manage my events and reach a wider audience.",
    avatar: "/placeholder.svg?height=100&width=100",
    rating: 5,
  },
  {
    id: "testimonial_3",
    name: "Emily Rodriguez",
    role: "Corporate Client",
    content:
      "We've hosted several corporate events using this service. The analytics and attendee management tools are top-notch.",
    avatar: "/placeholder.svg?height=100&width=100",
    rating: 4,
  },
]

// Stats for the dashboard
export const stats = {
  totalEvents: events.length,
  totalUsers: users.length,
  totalCategories: categories.length,
  totalAttendees: events.reduce((sum, event) => sum + event.attendees, 0),
}
